name: workflow 2

on:
  workflow_dispatch: #manual trigger


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Run Commsnd 
        run: node ./sendemail.js


      
